export const ACCOUNT_FAVORITE = "ACCOUNT/FAVORITE/LOAD";
export const ACCOUNT_FAVORITE_SUCCESS = "ACCOUNT/FAVORITE/LOAD_SUCCESS";
export const ACCOUNT_FAVORITE_FAIL = "ACCOUNT/FAVORITE/LOAD_FAIL";
export const ACCOUNT_FAVORITE_URL = "/3/account";

export const ACCOUNT_GETDETAILS = "ACCOUNT/GETDETAILS/LOAD";
export const ACCOUNT_GETDETAILS_SUCCESS = "ACCOUNT/GETDETAILS/LOAD_SUCCESS";
export const ACCOUNT_GETDETAILS_FAIL = "ACCOUNT/GETDETAILS/LOAD_FAIL";
export const ACCOUNT_GETDETAILS_URL = "/3/account";
