export const AUTHENTICATION_TOKEN_NEW = "AUTHENTICATION/TOKEN_NEW/LOAD";
export const AUTHENTICATION_TOKEN_NEW_SUCCESS =
  "AUTHENTICATION/TOKEN_NEW/LOAD_SUCCESS";
export const AUTHENTICATION_TOKEN_NEW_FAIL =
  "AUTHENTICATION/TOKEN_NEW/LOAD_FAIL";
export const AUTHENTICATION_TOKEN_NEW_URL = "/3/authentication/token/new";

export const AUTHENTICATION_SESSION_NEW = "AUTHENTICATION/SESSION_NEW/LOAD";
export const AUTHENTICATION_SESSION_NEW_SUCCESS =
  "AUTHENTICATION/SESSION_NEW/LOAD_SUCCESS";
export const AUTHENTICATION_SESSION_NEW_FAIL =
  "AUTHENTICATION/SESSION_NEW/LOAD_FAIL";
export const AUTHENTICATION_SESSION_NEW_URL = "/3/authentication/session/new";

export const AUTHENTICATION_TOKEN_VALIDATE_WITH_LOGIN =
  "AUTHENTICATION/TOKEN_VALIDATE_WITH_LOGIN/LOAD";
export const AUTHENTICATION_TOKEN_VALIDATE_WITH_LOGIN_SUCCESS =
  "AUTHENTICATION/TOKEN_VALIDATE_WITH_LOGIN/LOAD_SUCCESS";
export const AUTHENTICATION_TOKEN_VALIDATE_WITH_LOGIN_FAIL =
  "AUTHENTICATION/TOKEN_VALIDATE_WITH_LOGIN/LOAD_FAIL";
export const AUTHENTICATION_TOKEN_VALIDATE_WITH_LOGIN_URL =
  "/3/authentication/token/validate_with_login";
