export const GENRES_GET_MOVIE_LIST = "GENRES/GET_MOVIE_LIST/LOAD";
export const GENRES_GET_MOVIE_LIST_SUCCESS =
  "GENRES/GET_MOVIE_LIST/LOAD_SUCCESS";
export const GENRES_GET_MOVIE_LIST_FAIL = "GENRES/GET_MOVIE_LIST/LOAD_FAIL";
export const GENRES_GET_MOVIE_LIST_URL = "/3/genre/movie/list";
